module.exports = [
  {
    objectId: 12828,
    title: "The Sortie Made by the Garrison of Gibraltar",
    artistDisplayName: "John Trumbull",
    artistGender: "",
    primaryImage: "https://images.metmuseum.org/CRDImages/ad/original/DT61.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/DT61.jpg",
    endDate: 1789,
    country: "",
    culture: "American",
    isHighlight: true,
    isPublicDomain: true,
  },
  {
    objectId: 11133,
    title: "Prisoners from the Front",
    artistDisplayName: "Winslow Homer",
    artistGender: "",
    primaryImage: "https://images.metmuseum.org/CRDImages/ad/original/DT83.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/DT83.jpg",
    endDate: 1866,
    country: "",
    culture: "American",
    isHighlight: true,
    isPublicDomain: true,
  },
  {
    objectId: 11797,
    title: "The American School",
    artistDisplayName: "Matthew Pratt",
    artistGender: "",
    primaryImage: "https://images.metmuseum.org/CRDImages/ad/original/DT56.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/DT56.jpg",
    endDate: 1765,
    country: "",
    culture: "American",
    isHighlight: true,
    isPublicDomain: true,
  },
  {
    objectId: 10159,
    title: "Fur Traders Descending the Missouri",
    artistDisplayName: "George Caleb Bingham",
    artistGender: "",
    primaryImage: "https://images.metmuseum.org/CRDImages/ad/original/DT73.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/DT73.jpg",
    endDate: 1845,
    country: "",
    culture: "American",
    isHighlight: true,
    isPublicDomain: true,
  },
  {
    objectId: 10819,
    title: "The Champion Single Sculls (Max Schmitt in a Single Scull)",
    artistDisplayName: "Thomas Eakins",
    artistGender: "",
    primaryImage: "https://images.metmuseum.org/CRDImages/ad/original/DT86.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/DT86.jpg",
    endDate: 1871,
    country: "",
    culture: "American",
    isHighlight: true,
    isPublicDomain: true,
  },
  {
    objectId: 10554,
    title: "Watson and the Shark",
    artistDisplayName: "John Singleton Copley",
    artistGender: "",
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ad/original/DP140862.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/DP140862.jpg",
    endDate: 1778,
    country: "",
    culture: "American",
    isHighlight: true,
    isPublicDomain: true,
  },
  {
    objectId: 10464,
    title: "At the Seaside",
    artistDisplayName: "William Merritt Chase",
    artistGender: "",
    primaryImage: "https://images.metmuseum.org/CRDImages/ad/original/DT95.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/DT95.jpg",
    endDate: 1892,
    country: "",
    culture: "American",
    isHighlight: true,
    isPublicDomain: true,
  },
  {
    objectId: 11417,
    title: "Washington Crossing the Delaware",
    artistDisplayName: "Emanuel Leutze",
    artistGender: "",
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ad/original/DP215410.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/DP215410.jpg",
    endDate: 1851,
    country: "",
    culture: "American",
    isHighlight: true,
    isPublicDomain: true,
  },
  {
    objectId: 21126,
    title: "Young Husband: First Marketing",
    artistDisplayName: "Lilly Martin Spencer",
    artistGender: "Female",
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ad/original/DP355340.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/DP355340.jpg",
    endDate: 1854,
    country: "",
    culture: "American",
    isHighlight: true,
    isPublicDomain: true,
  },
  {
    objectId: 10154,
    title: "The Rocky Mountains, Lander's Peak",
    artistDisplayName: "Albert Bierstadt",
    artistGender: "",
    primaryImage: "https://images.metmuseum.org/CRDImages/ad/original/DT82.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/DT82.jpg",
    endDate: 1863,
    country: "",
    culture: "American",
    isHighlight: true,
    isPublicDomain: true,
  },
  {
    objectId: 16584,
    title: "George Washington",
    artistDisplayName: "Gilbert Stuart",
    artistGender: "",
    primaryImage: "https://images.metmuseum.org/CRDImages/ad/original/DT62.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/DT62.jpg",
    endDate: 1795,
    country: "",
    culture: "American",
    isHighlight: true,
    isPublicDomain: true,
  },
  {
    objectId: 765285,
    title: "Young Wife: First Stew",
    artistDisplayName: "Lilly Martin Spencer",
    artistGender: "Female",
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ad/original/Spencer_Young Wife - Copy.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/Spencer_Young Wife - Copy.jpg",
    endDate: 1854,
    country: "United States",
    culture: "American",
    isHighlight: true,
    isPublicDomain: true,
  },
  {
    objectId: 10522,
    title: "Daniel Crommelin Verplanck",
    artistDisplayName: "John Singleton Copley",
    artistGender: "",
    primaryImage: "https://images.metmuseum.org/CRDImages/ad/original/DT58.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/DT58.jpg",
    endDate: 1771,
    country: "",
    culture: "American",
    isHighlight: true,
    isPublicDomain: true,
  },
  {
    objectId: 11040,
    title: "Molly Wales Fobes",
    artistDisplayName: "Rufus Hathaway",
    artistGender: "",
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ad/original/DT2049.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/DT2049.jpg",
    endDate: 1790,
    country: "",
    culture: "American",
    isHighlight: true,
    isPublicDomain: true,
  },
  {
    objectId: 10830,
    title: "Elijah Boardman",
    artistDisplayName: "Ralph Earl",
    artistGender: "",
    primaryImage: "https://images.metmuseum.org/CRDImages/ad/original/DT60.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/DT60.jpg",
    endDate: 1789,
    country: "",
    culture: "American",
    isHighlight: true,
    isPublicDomain: true,
  },
  {
    objectId: 752047,
    title: "A Reconnaissance",
    artistDisplayName: "Frederic Remington",
    artistGender: "",
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ad/original/DP-19024-001.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/DP-19024-001.jpg",
    endDate: 1902,
    country: "",
    culture: "American",
    isHighlight: true,
    isPublicDomain: true,
  },
  {
    objectId: 14521,
    title: "Beauty Revealed",
    artistDisplayName: "Sarah Goodridge",
    artistGender: "Female",
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ad/original/DP141201.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/DP141201.jpg",
    endDate: 1828,
    country: "",
    culture: "American",
    isHighlight: true,
    isPublicDomain: true,
  },
  {
    objectId: 10534,
    title: "The Return of Neptune",
    artistDisplayName: "John Singleton Copley",
    artistGender: "",
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ad/original/DT201337.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/DT201337.jpg",
    endDate: 1754,
    country: "",
    culture: "American",
    isHighlight: false,
    isPublicDomain: true,
  },
  {
    objectId: 10785,
    title: "Ariadne",
    artistDisplayName: "Asher Brown Durand",
    artistGender: "",
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ad/original/DT213791.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/DT213791.jpg",
    endDate: 1835,
    country: "",
    culture: "American",
    isHighlight: false,
    isPublicDomain: true,
  },
  {
    objectId: 12699,
    title: "Musidora",
    artistDisplayName: "Thomas Sully",
    artistGender: "",
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ad/original/DT219411.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/DT219411.jpg",
    endDate: 1835,
    country: "",
    culture: "American",
    isHighlight: false,
    isPublicDomain: true,
  },
  {
    objectId: 10177,
    title: "Samuel Cutts",
    artistDisplayName: "Joseph Blackburn",
    artistGender: "",
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ad/original/ap1979.196.1.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/ap1979.196.1.jpg",
    endDate: 1763,
    country: "",
    culture: "American",
    isHighlight: false,
    isPublicDomain: true,
  },
  {
    objectId: 684606,
    title: "Boys Fishing",
    artistDisplayName: "Thomas Le Clear",
    artistGender: "",
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ad/original/DP-14224-001.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/DP-14224-001.jpg",
    endDate: 1846,
    country: "United States",
    culture: "American",
    isHighlight: false,
    isPublicDomain: true,
  },
  {
    objectId: 10524,
    title: "Gulian Verplanck",
    artistDisplayName: "John Singleton Copley",
    artistGender: "",
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ad/original/DT2032.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/DT2032.jpg",
    endDate: 1771,
    country: "United States",
    culture: "American",
    isHighlight: false,
    isPublicDomain: true,
  },
  {
    objectId: 10176,
    title: "Mrs. Samuel Cutts",
    artistDisplayName: "Joseph Blackburn",
    artistGender: "",
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ad/original/DT9848.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/DT9848.jpg",
    endDate: 1763,
    country: "",
    culture: "American",
    isHighlight: false,
    isPublicDomain: true,
  },
  {
    objectId: 10810,
    title: "Arcadia",
    artistDisplayName: "Thomas Eakins",
    artistGender: "",
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ad/original/DT221513.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/DT221513.jpg",
    endDate: 1883,
    country: "",
    culture: "American",
    isHighlight: false,
    isPublicDomain: true,
  },
  {
    objectId: 13338,
    title: "William Axtell",
    artistDisplayName: "John Wollaston",
    artistGender: "",
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ad/original/DT10223.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/DT10223.jpg",
    endDate: 1752,
    country: "",
    culture: "American",
    isHighlight: false,
    isPublicDomain: true,
  },
  {
    objectId: 13043,
    title: "The Calumny of Apelles",
    artistDisplayName: "John Vanderlyn",
    artistGender: "",
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ad/original/ap24.186.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/ap24.186.jpg",
    endDate: 1849,
    country: "",
    culture: "American",
    isHighlight: false,
    isPublicDomain: true,
  },
  {
    objectId: 11104,
    title: "Rats amongst the Barley Sheaves",
    artistDisplayName: "Thomas Hewes Hinckley",
    artistGender: "",
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ad/original/DT7414.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/DT7414.jpg",
    endDate: 1851,
    country: "",
    culture: "American",
    isHighlight: false,
    isPublicDomain: true,
  },
  {
    objectId: 11174,
    title: "The Bathers",
    artistDisplayName: "William Morris Hunt",
    artistGender: "",
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ad/original/ap36.99.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/ap36.99.jpg",
    endDate: 1877,
    country: "",
    culture: "American",
    isHighlight: false,
    isPublicDomain: true,
  },
  {
    objectId: 14400,
    title: "Portrait of a Gentleman",
    artistDisplayName: "Louis Francis DePaul Binsse",
    artistGender: "",
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ad/original/ap1991.91.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/ap1991.91.jpg",
    endDate: 1815,
    country: "United States",
    culture: "American",
    isHighlight: false,
    isPublicDomain: true,
  },
  {
    objectId: 15113,
    title: "Portrait of a Lady",
    artistDisplayName: "Anthony Meucci",
    artistGender: "",
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ad/original/APS6534.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/APS6534.jpg",
    endDate: 1837,
    country: "",
    culture: "American",
    isHighlight: false,
    isPublicDomain: true,
  },
  {
    objectId: 751622,
    title: "Autumn Scattering Leaves",
    artistDisplayName: "John La Farge",
    artistGender: "",
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ad/original/DP-13889-001.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/DP-13889-001.jpg",
    endDate: 1905,
    country: "",
    culture: "American",
    isHighlight: false,
    isPublicDomain: true,
  },
];
